### PR TITLE
Added my name

### PR DESCRIPTION
**Pull request by vpatiltech**
This pull request addresses issue no. #2

I ensure that before opening this pull request I have starred this repository.

Live link of GitHub Pages for my Fork is:
https://github.com/vpatiltech/Collaboration-For-Beginners

### CODE REVIEW

**Comment by udit-001** [comment]
Oops! Looks like you forgot to star this repo, please star this repo so that this pull request can be accepted.

**Comment by vpatiltech** [comment]
@udit-001 Resolved conflicts please approve

**Comment by udit-001** [comment]
Hey! Thanks for contributing to this project, We hope it was not a challenging task for you as a beginner. We hope to see you contribute in other open source projects in the future.

**Comment by vpatiltech** [comment]
Thanks Udit

Thanks and Regards,
Vinayak
- Sent from Zenfone

**Pull request merged**
